unqualified-search-registries = [
    'registry.access.redhat.com',
    'docker.io',
    'quay.io',
    "docker.1ms.run",
    "docker-0.unsee.tech",
    "lispy.org",
    "666860.xyz",
    "docker.m.daocloud.io",
    "demo.52013120.xyz",
    "proxy.vvvv.ee",
    "registry.cyou"
]
