#  ██████████ ████     ████ ██     ██ ██     ██
# ░░░░░██░░░ ░██░██   ██░██░██    ░██░░██   ██
#     ░██    ░██░░██ ██ ░██░██    ░██ ░░██ ██
#     ░██    ░██ ░░███  ░██░██    ░██  ░░███
#     ░██    ░██  ░░█   ░██░██    ░██   ██░██
#     ░██    ░██   ░    ░██░██    ░██  ██ ░░██
#     ░██    ░██        ░██░░███████  ██   ░░██
#     ░░     ░░         ░░  ░░░░░░░  ░░     ░░
#
#  ▓▓▓▓▓▓▓▓▓▓
# ░▓ Author ▓ Apple Shan <apple.shan@gmail.com>
# ░▓▓▓▓▓▓▓▓▓▓ create   : 2016-06-21
# ░░░░░░░░░░  modified : 2026-01-07

source-file ~/.config/tmux/settings.tmux
source-file ~/.config/tmux/style.tmux
source-file ~/.config/tmux/plugins.tmux
source-file ~/.config/tmux/mappings/root.tmux
source-file ~/.config/tmux/mappings/prefix.tmux
source-file ~/.config/tmux/mappings/copy-mode-vi.tmux
