monitor.alsa.rules = [
  {
    matches = [
      {
        device.nick = "HDA Intel PCH"  # 匹配Intel板载声卡
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = true        # 启用ALSA卡配置文件
        api.acp.auto-profile = false   # 禁用自动配置集切换
        api.acp.auto-port = false      # 禁用自动端口切换
        device.profile-set = "multiple.conf"  # 指定配置集文件
        device.profile = "multiple"    # 使用多路输出配置
      }
    }
  }
]