monitor.bluez.properties = {
  bluez5.enable-msbc = true
  bluez5.enable-sbc-xq = true
  bluez5.codecs = [ sbc sbc_xq ]
}

#monitor.bluez.properties = {
#    bluez5.codecs = [ldac]
#    bluez5.ldac-quality = hiq
#    bluez5.a2dp.ldac.effective-mtu = 1200
#    # 该配置强制蓝牙设备使用 LDAC 编码，并将传输单元增大至 1200 字节，提升传输稳定性。
#}