monitor.alsa.rules = [
  {
    matches = [
      {
        # 匹配所有输入设备
        node.name = "~alsa_input.*"
      },
      {
        # 匹配所有输出设备
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]

# 对于蓝牙设备
monitor.bluez.rules = [
  {
    matches = [
      {
        # 匹配所有蓝牙输入
        node.name = "~bluez_input.*"
      },
      {
        # 匹配所有蓝牙输出
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
