# 在这个时间段内累计的失败次数如果超过 deny，则触发锁定。
fail_interval = 900
# 在 fail_interval 间隔内，允许连续输错密码的次数。超过此数值，账户将被锁定。设置为 0 表示不锁定账户。
deny = 10
# 账户被锁定后，需要等待多久才能自动解锁。设置为 0 或 never 表示必须手动通过 faillock 命令解锁。
unlock_time = 30
