;=====================================================
;     module
;=====================================================

;==========================================================

[module/sep]
type = custom/text

format = |
;content-background = ${colors.background}
content-foreground = ${colors.foreground-alt}
content-padding = 0
format-padding = 0

[module/rofi-sxhkd-keybinds]
type = custom/text
format = ""
content-padding = 1
click-left = $HOME/.config/sxhkd/sxhkd-bindings d

[module/rofi-power-menu]
type = custom/text
format = ""
content-background = ${colors.shade-2}
content-foreground = ${colors.shade-5}
content-padding = 1
click-left = $HOME/.config/polybar/scripts/system-power-menu/rofi-power-menu.sh

;; -- Additional Formatting -- ;;
format-prefix = "  "

[module/rofi-applications]
type = custom/text
format = ""
content-padding = 1
click-left = rofi -show drun -columns 3

;==========================================================

[module/xtitle]
type = internal/xwindow
interval = 2
exec = echo "$(xtitle)"

; Available tokens:
;   %title%
; Default: %title%
label = %title%
label-maxlen = 100

;; -- Additional Formatting -- ;;

; Available tags:
;   <label> (default)
format = <label>
;format-background = #ooffffff
;format-foreground = #000
format-prefix = "  "
format-prefix-font = 2
format-prefix-foreground = ${colors.foreground}
format-padding = 1

[module/date]
type = internal/date
interval = 60

date = 📅
time =
date-alt = 📅 %Y-%m-%d%
time-alt = 🕒 %H:%M:%S

label = %date% %time%
label-padding = 0

;; -- Additional Formatting -- ;;

format = <label>
format-prefix = ""
format-suffix = ""

[module/memory]
type = internal/memory
interval = 2
format = <label><bar-used>
label = RAM

;; -- Additional Formatting -- ;;

;format-underline = #4bffdc

bar-used-width = 33
bar-used-foreground-0 = #5af78e
bar-used-foreground-1 = #5af78e
bar-used-foreground-2 = #f3f99d
bar-used-foreground-3 = #ff5c57
bar-used-fill = ▐
bar-used-empty = ▐
bar-used-empty-foreground = #444444
bar-used-indicator =

[module/memory2]
;https://github.com/jaagr/polybar/wiki/Module:-memory
type = internal/memory
interval = 2
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %gb_used%/%gb_free%

;; -- Additional Formatting -- ;;

format = RAM <label>
format-prefix = "  "
format-prefix-foreground = #3384d0
format-underline = #3384d0
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-padding = 1

[module/cpu]
type = internal/cpu
interval = 5

;; -- Additional Formatting -- ;;

;format = CPU <label> <ramp-coreload>
format = CPU <label>
format-prefix = " "
format-underline = #4bffdc

ramp-coreload-0 = ▁
ramp-coreload-0-font = 2
ramp-coreload-0-foreground = #aaff77
ramp-coreload-1 = ▂
ramp-coreload-1-font = 2
ramp-coreload-1-foreground = #aaff77
ramp-coreload-2 = ▃
ramp-coreload-2-font = 2
ramp-coreload-2-foreground = #aaff77
ramp-coreload-3 = ▄
ramp-coreload-3-font = 2
ramp-coreload-3-foreground = #aaff77
ramp-coreload-4 = ▅
ramp-coreload-4-font = 2
ramp-coreload-4-foreground = #fba922
ramp-coreload-5 = ▆
ramp-coreload-5-font = 2
ramp-coreload-5-foreground = #fba922
ramp-coreload-6 = ▇
ramp-coreload-6-font = 2
ramp-coreload-6-foreground = #ff5555
ramp-coreload-7 = █
ramp-coreload-7-font = 2
ramp-coreload-7-foreground = #ff5555

[module/info-trash]
type = custom/script
interval = 60
exec = ~/.config/polybar/scripts/info-trash/info-trash.sh
#click-left = /bin/sh -c "pcmanfm ~/.local/share/Trash/files" &
click-left = /bin/sh -c "thunar ~/.local/share/Trash/files" &
tail = true

;; -- Additional Formatting -- ;;

format =  <label>

[module/xkeyboard]
type = internal/xkeyboard

;; -- Additional Formatting -- ;;

; Available tags:
;   <label-layout> (default)
;   <label-indicator> (default)
format = <label-layout> <label-indicator>
format-prefix = " "
format-spacing = 0

; Available tokens:
;   %layout%
;   %name%
;   %number%
; Default: %layout%
label-layout = %layout%
label-layout-font = 0
label-layout-margin = 0

; Available tokens:
;   %name%
; Default: %name%
label-indicator-on = " %name%"
label-indicator-on-padding = 1
label-indicator-on-background = ${colors.secondary}
label-indicator-on-underline = ${colors.secondary}

; List of indicators to ignore
;blacklist-0 = num lock
blacklist-1 = scroll lock

[module/wired-network]
type = internal/network
interface = enp86s0
interval = 5.0
ping-interval = 30

;; -- Additional Formatting -- ;;

label-connected = %local_ip%    %downspeed%    %upspeed%
;label-disconnected = %ifname%
label-disconnected-foreground = ${colors.foreground-alt}

format-connected-prefix = ": "
format-connected-prefix-foreground = ${colors.foreground-alt}
;format-connected-underline = #55aa55
;format-disconnected-underline = ${self.format-connected-underline}

[module/wireless-network]
type = internal/network
interface = wlo1
interval = 5.0
ping-interval = 30

;; -- Additional Formatting -- ;;

label-connected = %local_ip%    %downspeed%    %upspeed%
;label-disconnected = ⚠ Not Connected
label-disconnected-foreground = ${colors.foreground-alt}

;format-connected = <ramp-signal> <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 

animation-packetloss-0 = 
animation-packetloss-0-foreground = #ffa64c
animation-packetloss-1 = 
animation-packetloss-1-foreground = ${bar/top.foreground}
animation-packetloss-framerate = 500

[module/wired-network-speedup]
type = internal/network
interface = ${module/wired-network.interface}

;; -- Additional Formatting -- ;;

label-connected = "%upspeed:7%"
format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = #5b

[module/wired-network-speeddown]
type = internal/network
interface = ${module/wired-network.interface}

;; -- Additional Formatting -- ;;

label-connected = "%downspeed:7%"
format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = #5b

[module/wireless-network-speedup]
type = internal/network
interface = ${module/wireless-network.interface}

;; -- Additional Formatting -- ;;

label-connected = "%upspeed:7%"
format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = #5b

[module/wireless-network-speeddown]
type = internal/network
interface = ${module/wireless-network.interface}

;; -- Additional Formatting -- ;;

label-connected = "%downspeed:7%"
format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = #5b

[module/system-cpu-temppercore]
type = custom/script
;exec = ~/.config/polybar/scripts/system-cpu-temppercore/system-cpu-temppercore.sh
exec = ~/.config/polybar/scripts/system-cpu-temppercore/tempcores.sh
interval = 5

;; -- Additional Formatting -- ;;

;format =  <label>
format-underline = ${colors.primary}

[module/system-fan-speed]
type = custom/script
exec = ~/.config/polybar/scripts/system-fan-speed/system-fan-speed.sh
interval = 10

[module/filesystem-home]
type = internal/fs
interval = 25

mount-0 = /home
label-mounted = "%{F#5b5b5b}%{F-} %percentage_used%%"

[module/filesystem-slash]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = "%{F#5b5b5b}%{F-} %percentage_used%%"
;label-mounted =  %mountpoint%: %percentage_used%%
;label-unmounted = %mountpoint% not mounted
;label-unmounted-foreground = #66
;label-unmounted-foreground = ${colors.foreground-alt}

[module/system-uptime-pretty]
type = custom/script
exec = ~/.config/polybar/scripts/system-uptime-pretty/system-uptime-pretty.sh
interval = 60

;; -- Additional Formatting -- ;;
format-prefix = "  "

[module/popup-calendar]
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar/popup-calendar.sh
interval = 60
;click-left = ~/.config/polybar/scripts/popup-calendar/popup-calendar.sh --popup &

;; https://github.com/ghost-in-the-machine-86/rofi-calendar
click-left = ~/.config/rofi/scripts/rofi-calendar/calendar &

;; -- Additional Formatting -- ;;

format-prefix = " "
format-suffix = " "

[module/release]
type = custom/script
exec = ~/.config/polybar/scripts/release/release.sh
interval = 6000

;; -- Additional Formatting -- ;;

;format-foreground = ${colors.foreground}
;format-background = ${colors.background}
format-prefix = "  "
format-prefix-foreground = #62FF00
;format-underline = #62FF00

[module/updates-arch-aur]
type = custom/script
exec = ~/.config/polybar/scripts/updates-arch-aur/updates-arch-aur.sh
interval = 600

[module/system-usb-udev]
type = custom/script
exec = ~/.config/polybar/scripts/system-usb-udev/system-usb-udev.sh
tail = true
click-left = ~/.config/polybar/scripts/system-usb-udev/system-usb-udev.sh --mount &
click-right = ~/.config/polybar/scripts/system-usb-udev/system-usb-udev.sh --unmount &

[module/system-usb-mount]
type = custom/script
exec = ~/.config/polybar/scripts/system-usb-mount/system-usb-mount.sh
interval = 5
click-left = ~/.config/polybar/scripts/system-usb-mount/system-usb-mount.sh --mount &
click-right = ~/.config/polybar/scripts/system-usb-mount/system-usb-mount.sh --unmount &

[module/rofi-usb-mount]
type = custom/script
exec = ~/.config/polybar/scripts/rofi-usb-mount/rofi-usb-mount.sh --check
tail = true
click-left = ~/.config/polybar/scripts/rofi-usb-mount/rofi-usb-mount.sh --mount
click-right = ~/.config/polybar/scripts/rofi-usb-mount/rofi-usb-mount.sh --umount
click-middle = ~/.config/polybar/scripts/rofi-usb-mount/rofi-usb-mount.sh --umount-all

[module/bluetooth]
type = custom/script
exec = ~/.config/rofi/scripts/rofi-bluetooth/rofi-bluetooth --status
interval = 5
label = %output%
click-left = ~/.config/rofi/scripts/rofi-bluetooth/rofi-bluetooth &

;; https://github.com/VineshReddy/polybar-redshift
[module/redshift]
type = custom/script
format-prefix = " "
exec = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift/redshift.sh temperature
click-left = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift/redshift.sh toggle
scroll-up = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift/redshift.sh increase
scroll-down = source ~/.config/polybar/scripts/env.sh && ~/.config/polybar/scripts/redshift/redshift.sh decrease
interval = 5

;; https://github.com/HankiGreed/playerctl-polybar
[module/polyplayer]
type = custom/script
exec = ~/.config/polybar/scripts/playerctl/polyplayer.sh
click-left = playerctl play-pause
click-right = ~/.config/rofi/scripts/rofi-playerctl/rofi-playerctl.sh
interval = 2

;; -- Additional Formatting -- ;;
format-prefix = "⏯️"
format-underline = #0a6cf5

[module/alerts]
type = custom/script
exec = ~/.config/polybar/scripts/alerts.sh output
click-left = ~/.config/polybar/scripts/alerts.sh show
click-right = ~/.config/polybar/scripts/alerts.sh toggle
interval = 5

;; -- Additional Formatting -- ;;

format-foreground = ${colors.primary}
format-padding = 1

[module/tray-panel]
type = internal/tray

format-margin = 4px
tray-spacing = 4px

[module/pipewire-volume]
type = custom/script
interval = 5

exec = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-volume.sh
click-left = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-volume.sh --toggle
scroll-up = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-volume.sh --increase
scroll-down = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-volume.sh --decrease
click-right = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-volume.sh --zerodb

label = " %output% "
format = <label>
format-foreground = ${colors.primary}

[module/pipewire-microphone]
type = custom/script
interval = 5

format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %output:3%

exec = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-microphone.sh
tail = true
click-left = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-microphone.sh --toggle
click-right = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-microphone.sh --zerodb
scroll-up = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-microphone.sh --increase
scroll-down = ~/.config/polybar/scripts/pipewire-wireplumber/pipewire-microphone.sh --decrease
