SRC=$HOME
DST=$HOME'/projects/private/dotfiles'

ARCHLINUX=$HOME'/projects/private/dotfiles/scripts/archlinux'

TARGETS=(
    aspell/.aspell.conf
    bat/.config/bat/config
    bin/.local/bin/ec
    bin/.local/bin/es
    bin/.local/bin/et
    bin/.local/bin/st
    bin/.local/bin/trash
    bin/.local/bin/trashctl
    bin/.local/bin/test-fonts.pl
    bin/.local/bin/serena-project-index.sh
    claude/.claude/CLAUDE.md
    claude/.claude/statusline.sh
    codex/.codex/AGENTS.md
    curl/.curlrc
    dunst/.config/dunst/dunstrc
    dunst/.config/dunst/dunstrc_dark-blood
    dunst/.config/dunst/dunstrc-sample
    dunst/.config/dunst/dunst-test
    editorconfig/.editorconfig
    fcitx5-rime/.config/environment.d/fcitx5.conf
    fcitx5-rime/.config/fcitx5/conf/classicui.conf
    fcitx5-rime/.config/fcitx5/conf/pinyin.conf
    fcitx5-rime/.config/fcitx5/conf/rime.conf
    feh/.config/feh/keys
    feh/.config/feh/wallpaper.sh
    # flatpak/var/lib/flatpak/repo/config
    font/.config/fontconfig/fonts.conf
    font/.config/fontconfig/source-han-for-noto-cjk.conf
    font/.config/fontconfig/web.conf
    font/.config/fontconfig/web-ui-fonts.conf
    font/.config/fontconfig/win-replacements.conf
    gemini/.gemini/.env
    gemini/.gemini/GEMINI.md
    ghostty/.config/ghostty/config
    git/.config/git/config
    git/.config/git/ignore
    git/.config/git/.gitmessage
    git/.config/git/conf/aliases.gitconfig
    git/.config/git/conf/colors.gitconfig
    git/.config/git/conf/settings.gitconfig
    git/.config/git/conf/urls.gitconfig
    git/.config/git/conf/user.gitconfig
    # gpg/.gnupg/gpg.conf
    # gpg/.gnupg/gpg-agent.conf
    i3wm/.config/i3/config
    i3wm/.config/i3/startup_apps.sh
    # i3wm/.config/i3/screenlayout/dual-screen
    # i3wm/.config/i3/screenlayout/monitor-toggle.sh
    # i3wm/.config/i3/screenlayout/single
    i3wm/.config/i3lock-fancy-multimonitor/lock
    #mimeapps/.config/mimeapps.list
    #mutt
    #nano/.config/nano/nanorc
    #nginx/etc/nginx/conf.d/log_format.conf
    #nginx/etc/nginx/sites-available/dojo-demos.conf
    #nginx/etc/nginx/sites-available/dojo-toolkit.conf
    #nginx/etc/nginx/sites-available/hello-nginx.conf
    #nginx/etc/nginx/sites-available/kpapi-51mch-com.conf
    #nginx/etc/nginx/sites-available/pdfdownload.conf
    #nginx/etc/nginx/sites-available/thinkitcms.conf
    nitrogen/.config/nitrogen/nitrogen.cfg
    nitrogen/.config/nitrogen/nitrogen.sh
    nitrogen/.config/nitrogen/nitrogen-change-all.sh
    npm/.npmrc
    #pacman/etc/pacman.d/hooks/clean_package_cache.hook
    #pacman/etc/pacman.d/archlinuxcn-mirrorlist
    #pacman/etc/pacman.d/mirrorlist
    #pacman/etc/pacman.d/mirrorlist.sync
    picom/.config/picom/picom.conf
    PipeWire/.config/pipewire/client.conf.d/20-upmix.conf
    PipeWire/.config/pipewire/client.conf.d/resample.conf
    PipeWire/.config/pipewire/pipewire.conf.d/10-sound.conf
    PipeWire/.config/pipewire/pipewire.conf.d/sink-eq11.conf
    PipeWire/.config/pipewire/pipewire-pulse.conf.d/20-upmix.conf
    PipeWire/.config/pipewire/pipewire-pulse.conf.d/switch-on-connect.conf
    PipeWire/.config/wireplumber/main.lua
    PipeWire/.config/wireplumber/wireplumber.conf.d/51-bluez-config.conf
    podman/.config/containers/registries.conf
    polybar/.config/polybar/launch.sh
    polybar/.config/polybar/config.ini
    polybar/.config/polybar/master.ini
    polybar/.config/polybar/modules.ini
    polybar/.config/polybar/workspaces.ini
    #polybar/.config/polybar/scripts/dnsmasq/dnsmasq
    polybar/.config/polybar/scripts/info-trash/info-trash.sh
    polybar/.config/polybar/scripts/pipewire-wireplumber/headphones_acpi_handler.sh
    polybar/.config/polybar/scripts/pipewire-wireplumber/pipewire.sh
    polybar/.config/polybar/scripts/pipewire-wireplumber/pipewire-volume.sh
    polybar/.config/polybar/scripts/pipewire-wireplumber/pipewire-microphone.sh
    polybar/.config/polybar/scripts/playerctl/polyplayer.sh
    polybar/.config/polybar/scripts/popup-calendar/popup-calendar.sh
    polybar/.config/polybar/scripts/pulseaudio-control/pulseaudio-control.bash
    polybar/.config/polybar/scripts/redshift/redshift.sh
    #polybar/.config/polybar/scripts/release/release.sh
    polybar/.config/polybar/scripts/system-cpu-temppercore/tempcores.sh
    #polybar/.config/polybar/scripts/system-fan-speed/system-fan-speed.sh
    polybar/.config/polybar/scripts/system-uptime-pretty/system-uptime-pretty.sh
    #polybar/.config/polybar/scripts/updates-arch-aur/updates-arch-aur.sh
    polybar/.config/polybar/scripts/alerts.sh
    proxychains/.proxychains/proxychains.conf
    python/.config/pip/pip.conf
    python/.condarc
    PaoPaoDNS/.config/systemd/user/container-paopaodns.service
    ranger/.config/ranger/rc.conf
    ranger/.config/ranger/scope.sh
    redshift/.config/redshift/redshift.sh
    redshift/.config/systemd/user/geoclue-agent.service
    ripgrep/.config/ripgrep/.ripgreprc
    rofi/.config/rofi/config
    rofi/.config/rofi/config.rasi
    #rofi/.config/rofi/scripts/monitor-settings/monitor_layout.sh
    #rofi/.config/rofi/scripts/monitor-settings/rofi-randr.sh
    #rofi/.config/rofi/scripts/monitor-settings/xrandrmenu.sh
    rofi/.config/rofi/scripts/rofi-bluetooth/rofi-bluetooth
    rofi/.config/rofi/scripts/rofi-book-selector/rofi-book-selector.sh
    rofi/.config/rofi/scripts/rofi-calendar/calendar
    rofi/.config/rofi/scripts/rofi-calendar/calendar.rasi
    rofi/.config/rofi/scripts/rofi-calendar/colors.rasi
    #rofi/.config/rofi/scripts/rofi-clipboard/rofi-clipboard.sh
    #rofi/.config/rofi/scripts/rofi-clipboard/scripts/dict
    #rofi/.config/rofi/scripts/rofi-clipboard/scripts/sed
    rofi/.config/rofi/scripts/rofi-media/media.sh
    rofi/.config/rofi/scripts/rofi-media/media.rasi
    rofi/.config/rofi/scripts/rofi-media/players.rasi
    rofi/.config/rofi/scripts/rofi-power-menu/rofi-power-menu
    shell/.zshrc
    shell/.oh-my-zsh/custom/zsh-theme.zsh
    shell/.oh-my-zsh/custom/shell-aliases.sh
    shell/.oh-my-zsh/custom/path.zsh
    shell/.oh-my-zsh/custom/functions.zsh
    shell/.oh-my-zsh/custom/emacs-functions.sh
    #shell/.oh-my-zsh/custom/completion/_ag
    #shell/.oh-my-zsh/custom/completion/_cmake
    #shell/.oh-my-zsh/custom/completion/_docker
    #shell/.oh-my-zsh/custom/completion/_pass
    #shell/.oh-my-zsh/custom/completion/maven-bash-completion.sh
    #shellcheck/.shellcheckrc
    #sift/.sift.conf
    ssh/.ssh/config
    #ssh/etc/ssh/sshd_config
    stow/.stow-global-ignore
    sxhkd/.config/sxhkd/sxhkdrc
    sxhkd/.config/sxhkd/sxhkd-bindings
    #terminator/.config/terminator/config
    #terminator/.config/terminator/plugins/logger.py
    #terminator/.config/terminator/plugins/searchplugin.py
    tmux/.config/tmux/tmux.conf
    tmux/.config/tmux/settings.tmux
    tmux/.config/tmux/plugins.tmux
    tmux/.config/tmux/style.tmux
    tmux/.config/tmux/mappings/copy-mode-vi.tmux
    tmux/.config/tmux/mappings/prefix.tmux
    tmux/.config/tmux/mappings/root.tmux
    #tor/.arm/torrc
    #urlview/.urlview
    urxvt/.Xdefaults
    urxvt/.Xresources.d/blaquemagick.Xcolors
    urxvt/.Xresources.d/blizzard-orb.Xcolors
    urxvt/.Xresources.d/miasma.Xcolors
    urxvt/.Xresources.d/sourcerer.Xcolors
    urxvt/.urxvt/ext/clipboard
    urxvt/.urxvt/ext/config-print
    urxvt/.urxvt/ext/config-reload
    vscode/.config/Code/User/settings.json
    #wget/.wgetrc
    xorg/.profile
    #xorg/.xinitrc
    xorg/.xprofile
    xorg/.Xresources
    xorg/.Xresources.d/Xresources.colors
    xorg/.Xresources.d/Xresources.xcursor
    xorg/.Xresources.d/Xresources.xft
    xorg/.Xresources.d/Xresources.xterm
    #xorg/etc/X11/xorg.conf.d/00-fonts.conf
    #xorg/etc/X11/xorg.conf.d/00-keyboard.conf
    #xorg/etc/X11/xorg.conf.d/10-magic-trackpad2.conf
    #xorg/etc/X11/xorg.conf.d/10-monitor.conf
    #xorg/etc/X11/xorg.conf.d/20-intel.conf
    #xorg/etc/X11/xorg.conf.d/30-touchpad.conf
    #xorg/etc/X11/xorg.conf.d/90-mouse.conf
    yay/.config/yay/config.json
    #youtube-dl/youtube-dl.conf
)
