context.properties = {
    default.clock.rate = 48000
    default.clock.allowed-rates = [ 22050 44100 48000 16000 ]
    default.clock.min-quantum = 16
    default.clock.quantum = 4096
    default.clock.max-quantum = 8192
}